### ISSUE TITLE
Тест на управление пресетами

### ISSUE THREAD

**Issue by BlackWrangler** [GolosMovement/QA-electoral.graphics#14]
После теста #6  

**Создание пресета**

- [x] Пользователь заходит на страницу Presets Manager (напр. https://laboratoryweb.azurewebsites.net/presets ) [Прототип](https://www.justinmind.com/usernote/tests/32387290/35551603/35573897/index.html#/screens/de8aaed3-307f-48ae-bb6b-c0071a9c0889): 
- [x] П. выбирает набор протоколов созданный в тесте #6 (Дума 2011)
- [x] П. добавляет пресет с 
  - **Заголовок (рус):** "Явка % тест"
  - **Формула:**  ('бюллетеней выдано досрочно'+'выдано на УИК'+'выдано бюллетеней мобильно'))/'Избирателей в списке'
  - остальные описательные поля произвольны (включая таблицу использования пресета в инструментах).
- [x] Система сохраняет настройки пресета и отражает его на странице.

**Проверка работы** 

- [x] Пользователь переходит в тестовый GBD (в iteration 2, потом будет полноценный GBD)
- [x] Выбирает набор протоколов созданный в тесте #6
- [x] Задает выборку 

Республика Ингушетия | Назрановская городская
  -- | --

Задает параметр для анализа: "Явка % тест"
- [x] Получает картину
![image](https://user-images.githubusercontent.com/36114863/48348880-3e9b2e00-e68b-11e8-8c1f-3ab46c83252a.png)

- [x] Выборочно проверяет цифры. Цифры должны быть 

93.83% | 96.58% | 85.72% | 93.15% | 80.62% | 85.06% | 85.36% | 84.89% | 85.08% | 85.14% | 85.14% | 95.82% | 85.32% | 85.39% | 85.40% | 83.30% | 85.32% | 85.21% | 84.89%
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --

**Проверка скорости работы** 

- [x]  Пользователь задает выборку
  - "город Москва" (это самый многочисленный регион, но желательно: для РФ) 
  - Задает параметр для анализа "Явка % тест"

- [x] Система строит диаграмму за 5 секунд (желательно для РФ до 30 секунд. [SQL запрос получает данные до 12 секунд](https://github.com/GolosMovement/StatElectGenerator/issues/86), какое-то время займет создание JS for HighChart. Но мы замеряем корректность и скорость работы пресетов)

**Проверка редактирования пресета**

- [ ] Пользователь заходит на страницу Presets Manager (напр. https://laboratoryweb.azurewebsites.net/presets)
- [ ] П. выбирает набор протоколов созданный в тесте #6 (Дума 2011)
- [ ] П. добавляет пресет с 
  - **Заголовок (рус):** "ЛДПР % тест"
  - **Формула:**  ('ЛДПР'/'Недействительных'+'Действительных' )

- [ ] Система сохраняет пресет и отражает его на странице.

**Проверка работы отредактированного пресета** 

- [ ] Пользователь переходит в тестовый GBD (в iteration 2, потом будет полноценный GBD)
- [ ] Выбирает набор протоколов созданный в тесте #6
- [ ] Задает выборку 

Республика Карелия |   | Петрозаводская городская №3 (судовая)
-- | -- | --

- [ ] П. задает параметр для анализа "ЛДПР % тест"

- [ ] С. выдает картину похожу на 
![image](https://user-images.githubusercontent.com/36114863/48350591-604ae400-e690-11e8-861c-3a56a505d578.png)

- [ ] П. выборочно проверяет  числа. Первые числа должны быть:

50.00% | 8.33% | 0.00% | 8.33% | 36.36% | 45.45% | 44.44% | 40.00% | 42.86% | 44.44%
-- | -- | -- | -- | -- | -- | -- | -- | -- | --

- [ ] П. проверяет отсутствие отменённых или несостоявшихся выборов. Таких участков не должно быть:

УИК №701 | УИК №703 | УИК №708 | УИК №713 | УИК №720 | УИК №734 | УИК №743
-- | -- | -- | -- | -- | -- | --

**Проверка удаления**

- [ ] Пользователь заходит на страницу Presets Manager (напр. https://laboratoryweb.azurewebsites.net/presets)
- [ ] П. выбирает набор протоколов созданный в тесте #6 (Дума 2011)
- [ ] П. удаляет пресет  "ЛДПР % тест"
- [ ] Система удаляет пресет и отражает это на странице.

**Comment by bytematepro** [comment]
**Создание пресета**
Расчет пресета "Явка % тест" длится 1 минуту 30 секунд.

**Проверка скорости работы**
"город Москва" построение диаграммы 19 с.

**Проверка редактирования пресета**
После добавления пресета "ЛДПР % тест", с формулой:('ЛДПР'/('Недействительных'+'Действительных' ))
Расчет пресета завершается с ошибкой "Server error" через 2 минуты.

**Comment by bytematepro** [comment]
2-ая итерация
Повторил тест на импортированных сегодня  данных QA #6-2. Расчет завершается через 2 минуты с сообщением: "Server error!", для всех случаев "Явка % тест" и  "ЛДПР % тест".
При построении GBDV не отображается график. Проверял в разных браузерах.
